In [36]:
import pandas as pd
import json
import glob

In [37]:
results_dir = '../results'

In [89]:
all_results = glob.glob('../results/*.json')

table_data = []
for result in all_results:
    with open(result, 'r') as f:
        data = json.load(f)
        for k, v in data.items():
            if k in ['Accuracy', 'IoU', 'AP']:
                data[k] = v['mean']        
            if k == 'train_config':
                v = str(v)
                if '[' in v:
                    data[k] = 15
                elif '5' in v:
                    data[k] = 5
                else:
                    data[k] = 2
            if k == 'window_len':
                data['window_len'] = int(v)
        table_data.append(data)

In [90]:
df = pd.DataFrame(table_data)
df.head()

,AP,IoU,Accuracy,number_of_samples,depth_channel_representation_mode,window_len,train_config,multiple_digits,model_path
0,0.206345,0.221674,0.919198,1907,original,20,2,False,C:\Users\Emiel\Documents\TU\dsait4205-ev-mask-...
1,0.359727,0.455038,0.953592,1907,original,20,5,False,C:\Users\Emiel\Documents\TU\dsait4205-ev-mask-...
2,0.423964,0.570064,0.962117,1907,original,20,15,False,C:\Users\Emiel\Documents\TU\dsait4205-ev-mask-...
3,0.173465,0.164156,0.922380,2525,original,10,2,False,C:\Users\Emiel\Documents\TU\dsait4205-ev-mask-...
4,0.190495,0.204647,0.929361,2525,original,10,2,False,C:\Users\Emiel\Documents\TU\dsait4205-ev-mask-...

In [91]:
metrics = ['Accuracy', 'IoU', 'AP']
grouped = df.groupby(['window_len','train_config','multiple_digits','depth_channel_representation_mode'])
means = grouped[metrics].mean(numeric_only=True)
stds = grouped[metrics].std(numeric_only=True)
stds.rename(columns=lambda x: x + '_std', inplace=True)
counts = pd.DataFrame(grouped.size(), columns=['n'])

combined = pd.concat([means, stds, counts], axis=1)
for metric in metrics:
    combined[metric] = combined.apply(lambda x: f"{x[metric]*100:.2f} ± {x[f'{metric}_std']*100:.2f}", axis=1)
    combined.drop([f'{metric}_std'], axis=1, inplace=True)
combined.to_csv('results.csv', index=True)
combined

                                                                               Accuracy  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           93.37 ± 0.71
           5            False           original                           94.93 ± 0.29
           15           False           original                           96.06 ± 0.11
20         2            False           original                           93.16 ± 1.18
           5            False           original                           95.25 ± 0.18
           15           False           original                           96.18 ± 0.04
50         2            False           original                           90.39 ± 3.63
           5            False           original                           93.10 ± 3.97
           15           False           original                           96.14 ± 0.05

                                                                                     IoU  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                            21.08 ± 3.31
           5            False           original                            38.55 ± 3.30
           15           False           original                            55.21 ± 2.05
20         2            False           original                            19.18 ± 4.86
           5            False           original                            42.46 ± 2.27
           15           False           original                            55.93 ± 1.22
50         2            False           original                            17.01 ± 7.61
           5            False           original                           35.63 ± 14.81
           15           False           original                            55.23 ± 1.05

                                                                                      AP  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                            19.92 ± 2.34
           5            False           original                            31.79 ± 2.09
           15           False           original                            40.23 ± 1.05
20         2            False           original                            18.65 ± 3.26
           5            False           original                            33.99 ± 1.40
           15           False           original                            41.53 ± 0.76
50         2            False           original                            18.12 ± 6.83
           5            False           original                           29.22 ± 12.22
           15           False           original                            42.25 ± 0.76

                                                                           n
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           6
           5            False           original                           6
           15           False           original                           6
20         2            False           original                           6
           5            False           original                           6
           15           False           original                           6
50         2            False           original                           6
           5            False           original                           6
           15           False           original                           5

# Reference results

In [92]:
paper_results = """
window_len,train_config,multiple_digits,depth_channel_representation_mode,Accuracy,IoU,AP
10,2,False,original,93.33,14.19,13.4
10,5,False,original,95.04,41.05,32.8
10,15,False,original,95.64,55.47,42.3
20,2,False,original,94.23,20.48,18.7
20,5,False,original,95.63,47.24,37.1
20,15,False,original,96.29,58.01,43.2
50,2,False,original,94.76,27.82,23.7
50,5,False,original,95.27,41.73,35.2
50,15,False,original,96.51,60.29,44.6
"""
import io
paper_df = pd.read_csv(io.StringIO(paper_results))
paper_df = paper_df.groupby(['window_len','train_config','multiple_digits','depth_channel_representation_mode']).mean() / 100
paper_df.head()

                                                                           Accuracy  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                             0.9333
           5            False           original                             0.9504
           15           False           original                             0.9564
20         2            False           original                             0.9423
           5            False           original                             0.9563

                                                                              IoU  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           0.1419
           5            False           original                           0.4105
           15           False           original                           0.5547
20         2            False           original                           0.2048
           5            False           original                           0.4724

                                                                              AP
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           0.134
           5            False           original                           0.328
           15           False           original                           0.423
20         2            False           original                           0.187
           5            False           original                           0.371

# T-Test

In [ ]:
from scipy import stats
import numpy as np

# Ensure all DataFrames have the same index
common_index = paper_df.index.intersection(means.index)

# Perform 1-sample t-test for each metric
metrics = ['Accuracy', 'IoU', 'AP']
t_test_results = {}

print("T-test Results:")
print("H0: Our results = Paper results")
print("H1: Our results ≠ Paper results")
print("\nSignificance levels: * p<0.05, ** p<0.01, *** p<0.001")
print("\nResults (t-statistic, p-value):")

for metric in metrics:
    print(f"\n--- {metric} ---")
    t_test_results[metric] = {}
    
    for idx in common_index:
        # Get our sample data (mean and std)
        our_mean = means.loc[idx, metric]
        our_std = stds.loc[idx, f'{metric}_std']
        
        # Get paper (expected) mean
        paper_mean = paper_df.loc[idx, metric]
        
        n = 6  # You can adjust this if you have the actual sample sizes
        
        # Calculate t-statistic for 1-sample t-test
        # t = (sample_mean - population_mean) / (sample_std / sqrt(n))
        t_stat = (our_mean - paper_mean) / (our_std / np.sqrt(n))
        
        # Calculate p-value (two-tailed test)
        p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df=n-1))
        
        # Store results
        t_test_results[metric][idx] = {
            't_statistic': t_stat,
            'p_value': p_value,
            'our_mean': our_mean,
            'paper_mean': paper_mean,
            'our_std': our_std
        }
        
        # Determine significance level
        if p_value < 0.001:
            sig = "***"
        elif p_value < 0.01:
            sig = "**"
        elif p_value < 0.05:
            sig = "*"
        else:
            sig = ""
        
        print(f"{idx}: t={t_stat:.3f}, p={p_value:.3f}{sig}")
        print(f"  Our: {our_mean:.2f}±{our_std:.2f}% vs Paper: {paper_mean:.2f}%")

# Summary statistics
print("\n" + "="*50)
print("SUMMARY")
print("="*50)

for metric in metrics:
    p_values = [result['p_value'] for result in t_test_results[metric].values()]
    significant_count = sum(1 for p in p_values if p < 0.05)
    
    print(f"\n{metric}:")
    print(f"  Total comparisons: {len(p_values)}")
    print(f"  Significant differences (p<0.05): {significant_count}")
    print(f"  Non-significant: {len(p_values) - significant_count}")

T-test Results:
H0: Our results = Paper results
H1: Our results ≠ Paper results

Significance levels: * p<0.05, ** p<0.01, *** p<0.001

Results (t-statistic, p-value):

--- Accuracy ---
(10, 2, False, 'original'): t=0.146, p=0.889
  Our: 0.93±0.01% vs Paper: 0.93%
(10, 5, False, 'original'): t=-0.931, p=0.394
  Our: 0.95±0.00% vs Paper: 0.95%
(10, 15, False, 'original'): t=9.427, p=0.000***
  Our: 0.96±0.00% vs Paper: 0.96%
(20, 2, False, 'original'): t=-2.235, p=0.076
  Our: 0.93±0.01% vs Paper: 0.94%
(20, 5, False, 'original'): t=-5.168, p=0.004**
  Our: 0.95±0.00% vs Paper: 0.96%
(20, 15, False, 'original'): t=-6.431, p=0.001**
  Our: 0.96±0.00% vs Paper: 0.96%
(50, 2, False, 'original'): t=-2.951, p=0.032*
  Our: 0.90±0.04% vs Paper: 0.95%
(50, 5, False, 'original'): t=-1.340, p=0.238
  Our: 0.93±0.04% vs Paper: 0.95%
(50, 15, False, 'original'): t=-17.197, p=0.000***
  Our: 0.96±0.00% vs Paper: 0.97%

--- IoU ---
(10, 2, False, 'original'): t=5.101, p=0.004**
  Our: 0.21±0.03% vs Paper: 0.14%
(10, 5, False, 'original'): t=-1.859, p=0.122
  Our: 0.39±0.03% vs Paper: 0.41%
(10, 15, False, 'original'): t=-0.307, p=0.771
  Our: 0.55±0.02% vs Paper: 0.55%
(20, 2, False, 'original'): t=-0.653, p=0.542
  Our: 0.19±0.05% vs Paper: 0.20%
(20, 5, False, 'original'): t=-5.158, p=0.004**
  Our: 0.42±0.02% vs Paper: 0.47%
(20, 15, False, 'original'): t=-4.179, p=0.009**
  Our: 0.56±0.01% vs Paper: 0.58%
(50, 2, False, 'original'): t=-3.478, p=0.018*
  Our: 0.17±0.08% vs Paper: 0.28%
(50, 5, False, 'original'): t=-1.008, p=0.360
  Our: 0.36±0.15% vs Paper: 0.42%
(50, 15, False, 'original'): t=-11.847, p=0.000***
  Our: 0.55±0.01% vs Paper: 0.60%

--- AP ---
(10, 2, False, 'original'): t=6.831, p=0.001**
  Our: 0.20±0.02% vs Paper: 0.13%
(10, 5, False, 'original'): t=-1.191, p=0.287
  Our: 0.32±0.02% vs Paper: 0.33%
(10, 15, False, 'original'): t=-4.846, p=0.005**
  Our: 0.40±0.01% vs Paper: 0.42%
(20, 2, False, 'original'): t=-0.037, p=0.972
  Our: 0.19±0.03% vs Paper: 0.19%
(20, 5, False, 'original'): t=-5.435, p=0.003**
  Our: 0.34±0.01% vs Paper: 0.37%
(20, 15, False, 'original'): t=-5.353, p=0.003**
  Our: 0.42±0.01% vs Paper: 0.43%
(50, 2, False, 'original'): t=-2.000, p=0.102
  Our: 0.18±0.07% vs Paper: 0.24%
(50, 5, False, 'original'): t=-1.198, p=0.285
  Our: 0.29±0.12% vs Paper: 0.35%
(50, 15, False, 'original'): t=-7.574, p=0.001***
  Our: 0.42±0.01% vs Paper: 0.45%

==================================================
SUMMARY
==================================================

Accuracy:
  Total comparisons: 9
  Significant differences (p<0.05): 5
  Non-significant: 4

IoU:
  Total comparisons: 9
  Significant differences (p<0.05): 5
  Non-significant: 4

AP:
  Total comparisons: 9
  Significant differences (p<0.05): 5
  Non-significant: 4

# Holm-Bonferroni

In [98]:
from statsmodels.stats.multitest import multipletests
import pandas as pd

# Collect all p-values and their corresponding information
all_tests = []
for metric in metrics:
    for idx, result in t_test_results[metric].items():
        all_tests.append({
            'metric': metric,
            'configuration': idx,
            'p_value': result['p_value'],
            't_statistic': result['t_statistic'],
            'our_mean': result['our_mean'],
            'paper_mean': result['paper_mean'],
            'our_std': result['our_std']
        })

# Extract p-values for correction
p_values = [test['p_value'] for test in all_tests]

# Apply Holm-Bonferroni correction
rejected, p_corrected, alpha_sidak, alpha_bonf = multipletests(
    p_values, 
    alpha=0.05, 
    method='holm'
)

# Add corrected results back to our test data
for i, test in enumerate(all_tests):
    test['p_corrected'] = p_corrected[i]
    test['rejected_holm'] = rejected[i]

print("HOLM-BONFERRONI CORRECTED RESULTS")
print("="*60)
print("H0: Our results = Paper results")
print("H1: Our results ≠ Paper results")
print(f"Total number of tests: {len(p_values)}")
print(f"Family-wise error rate (FWER) controlled at α = 0.05")
print("\nSignificance levels: * p_corrected<0.05, ** p_corrected<0.01, *** p_corrected<0.001")
print("\nResults (t-statistic, p_original → p_corrected, significant):")

# Display results organized by metric
for metric in metrics:
    print(f"\n--- {metric} ---")
    
    metric_tests = [test for test in all_tests if test['metric'] == metric]
    
    for test in metric_tests:
        # Determine significance level for corrected p-value
        if test['p_corrected'] < 0.001:
            sig = "***"
        elif test['p_corrected'] < 0.01:
            sig = "**"
        elif test['p_corrected'] < 0.05:
            sig = "*"
        else:
            sig = ""
        
        # Show if hypothesis was rejected
        rejected_status = "SIGNIFICANT" if test['rejected_holm'] else "not significant"
        
        print(f"{test['configuration']}:")
        print(f"  t={test['t_statistic']:.3f}, p={test['p_value']:.3f} → p_corrected={test['p_corrected']:.3f}{sig}")
        print(f"  Our: {test['our_mean']*100:.2f}±{test['our_std']*100:.2f}% vs Paper: {test['paper_mean']*100:.2f}%")
        print(f"  Result: {rejected_status}")

# Summary statistics
print("\n" + "="*60)
print("SUMMARY - HOLM-BONFERRONI CORRECTED")
print("="*60)

total_significant_original = sum(1 for test in all_tests if test['p_value'] < 0.05)
total_significant_corrected = sum(1 for test in all_tests if test['rejected_holm'])

print(f"Total tests performed: {len(all_tests)}")
print(f"Significant before correction (p<0.05): {total_significant_original}")
print(f"Significant after Holm-Bonferroni correction: {total_significant_corrected}")
print(f"Reduction due to multiple comparisons correction: {total_significant_original - total_significant_corrected}")

# Summary by metric
for metric in metrics:
    metric_tests = [test for test in all_tests if test['metric'] == metric]
    original_sig = sum(1 for test in metric_tests if test['p_value'] < 0.05)
    corrected_sig = sum(1 for test in metric_tests if test['rejected_holm'])
    
    print(f"\n{metric}:")
    print(f"  Total comparisons: {len(metric_tests)}")
    print(f"  Significant before correction: {original_sig}")
    print(f"  Significant after correction: {corrected_sig}")
    print(f"  Proportion significant after correction: {corrected_sig/len(metric_tests):.1%}")

# Create a summary DataFrame for easy viewing
summary_df = pd.DataFrame(all_tests)
summary_df['configuration_str'] = summary_df['configuration'].astype(str)
summary_df['significant_original'] = summary_df['p_value'] < 0.05
summary_df['significant_corrected'] = summary_df['rejected_holm']

print(f"\nDetailed results saved in 'summary_df' DataFrame with columns:")
print(f"  {list(summary_df.columns)}")

# Optional: Save detailed results to CSV
summary_df.to_csv('holm_bonferroni_results.csv', index=False)
print(f"\nDetailed results saved to 'holm_bonferroni_results.csv'")

HOLM-BONFERRONI CORRECTED RESULTS
============================================================
H0: Our results = Paper results
H1: Our results ≠ Paper results
Total number of tests: 27
Family-wise error rate (FWER) controlled at α = 0.05

Significance levels: * p_corrected<0.05, ** p_corrected<0.01, *** p_corrected<0.001

Results (t-statistic, p_original → p_corrected, significant):

--- Accuracy ---
(10, 2, False, 'original'):
  t=0.146, p=0.889 → p_corrected=1.000
  Our: 93.37±0.71% vs Paper: 93.33%
  Result: not significant
(10, 5, False, 'original'):
  t=-0.931, p=0.394 → p_corrected=1.000
  Our: 94.93±0.29% vs Paper: 95.04%
  Result: not significant
(10, 15, False, 'original'):
  t=9.427, p=0.000 → p_corrected=0.006**
  Our: 96.06±0.11% vs Paper: 95.64%
  Result: SIGNIFICANT
(20, 2, False, 'original'):
  t=-2.235, p=0.076 → p_corrected=0.908
  Our: 93.16±1.18% vs Paper: 94.23%
  Result: not significant
(20, 5, False, 'original'):
  t=-5.168, p=0.004 → p_corrected=0.068
  Our: 95.25±0.18% vs Paper: 95.63%
  Result: not significant
(20, 15, False, 'original'):
  t=-6.431, p=0.001 → p_corrected=0.030*
  Our: 96.18±0.04% vs Paper: 96.29%
  Result: SIGNIFICANT
(50, 2, False, 'original'):
  t=-2.951, p=0.032 → p_corrected=0.414
  Our: 90.39±3.63% vs Paper: 94.76%
  Result: not significant
(50, 5, False, 'original'):
  t=-1.340, p=0.238 → p_corrected=1.000
  Our: 93.10±3.97% vs Paper: 95.27%
  Result: not significant
(50, 15, False, 'original'):
  t=-17.197, p=0.000 → p_corrected=0.000***
  Our: 96.14±0.05% vs Paper: 96.51%
  Result: SIGNIFICANT

--- IoU ---
(10, 2, False, 'original'):
  t=5.101, p=0.004 → p_corrected=0.068
  Our: 21.08±3.31% vs Paper: 14.19%
  Result: not significant
(10, 5, False, 'original'):
  t=-1.859, p=0.122 → p_corrected=1.000
  Our: 38.55±3.30% vs Paper: 41.05%
  Result: not significant
(10, 15, False, 'original'):
  t=-0.307, p=0.771 → p_corrected=1.000
  Our: 55.21±2.05% vs Paper: 55.47%
  Result: not significant
(20, 2, False, 'original'):
  t=-0.653, p=0.542 → p_corrected=1.000
  Our: 19.18±4.86% vs Paper: 20.48%
  Result: not significant
(20, 5, False, 'original'):
  t=-5.158, p=0.004 → p_corrected=0.068
  Our: 42.46±2.27% vs Paper: 47.24%
  Result: not significant
(20, 15, False, 'original'):
  t=-4.179, p=0.009 → p_corrected=0.130
  Our: 55.93±1.22% vs Paper: 58.01%
  Result: not significant
(50, 2, False, 'original'):
  t=-3.478, p=0.018 → p_corrected=0.248
  Our: 17.01±7.61% vs Paper: 27.82%
  Result: not significant
(50, 5, False, 'original'):
  t=-1.008, p=0.360 → p_corrected=1.000
  Our: 35.63±14.81% vs Paper: 41.73%
  Result: not significant
(50, 15, False, 'original'):
  t=-11.847, p=0.000 → p_corrected=0.002**
  Our: 55.23±1.05% vs Paper: 60.29%
  Result: SIGNIFICANT

--- AP ---
(10, 2, False, 'original'):
  t=6.831, p=0.001 → p_corrected=0.024*
  Our: 19.92±2.34% vs Paper: 13.40%
  Result: SIGNIFICANT
(10, 5, False, 'original'):
  t=-1.191, p=0.287 → p_corrected=1.000
  Our: 31.79±2.09% vs Paper: 32.80%
  Result: not significant
(10, 15, False, 'original'):
  t=-4.846, p=0.005 → p_corrected=0.075
  Our: 40.23±1.05% vs Paper: 42.30%
  Result: not significant
(20, 2, False, 'original'):
  t=-0.037, p=0.972 → p_corrected=1.000
  Our: 18.65±3.26% vs Paper: 18.70%
  Result: not significant
(20, 5, False, 'original'):
  t=-5.435, p=0.003 → p_corrected=0.060
  Our: 33.99±1.40% vs Paper: 37.10%
  Result: not significant
(20, 15, False, 'original'):
  t=-5.353, p=0.003 → p_corrected=0.061
  Our: 41.53±0.76% vs Paper: 43.20%
  Result: not significant
(50, 2, False, 'original'):
  t=-2.000, p=0.102 → p_corrected=1.000
  Our: 18.12±6.83% vs Paper: 23.70%
  Result: not significant
(50, 5, False, 'original'):
  t=-1.198, p=0.285 → p_corrected=1.000
  Our: 29.22±12.22% vs Paper: 35.20%
  Result: not significant
(50, 15, False, 'original'):
  t=-7.574, p=0.001 → p_corrected=0.015*
  Our: 42.25±0.76% vs Paper: 44.60%
  Result: SIGNIFICANT

============================================================
SUMMARY - HOLM-BONFERRONI CORRECTED
============================================================
Total tests performed: 27
Significant before correction (p<0.05): 15
Significant after Holm-Bonferroni correction: 6
Reduction due to multiple comparisons correction: 9

Accuracy:
  Total comparisons: 9
  Significant before correction: 5
  Significant after correction: 3
  Proportion significant after correction: 33.3%

IoU:
  Total comparisons: 9
  Significant before correction: 5
  Significant after correction: 1
  Proportion significant after correction: 11.1%

AP:
  Total comparisons: 9
  Significant before correction: 5
  Significant after correction: 2
  Proportion significant after correction: 22.2%

Detailed results saved in 'summary_df' DataFrame with columns:
  ['metric', 'configuration', 'p_value', 't_statistic', 'our_mean', 'paper_mean', 'our_std', 'p_corrected', 'rejected_holm', 'configuration_str', 'significant_original', 'significant_corrected']

Detailed results saved to 'holm_bonferroni_results.csv'

# Results Tables

In [100]:
# Reshape results back to original table format
def create_results_table(all_tests, value_column, metrics):
    """Helper function to create a table with original indexing"""
    results_dict = {}
    
    for test in all_tests:
        config = test['configuration']
        metric = test['metric']
        value = test[value_column]
        
        if config not in results_dict:
            results_dict[config] = {}
        results_dict[config][metric] = value
    
    # Convert to DataFrame with proper indexing
    results_df = pd.DataFrame.from_dict(results_dict, orient='index')
    results_df = results_df.reindex(columns=metrics)  # Ensure column order
    return results_df

# Create tables for different aspects of the results
metrics = ['Accuracy', 'IoU', 'AP']

# Table 1: Original p-values
p_values_table = create_results_table(all_tests, 'p_value', metrics)

# Table 2: Holm-Bonferroni corrected p-values
p_corrected_table = create_results_table(all_tests, 'p_corrected', metrics)

# Table 3: T-statistics
t_stats_table = create_results_table(all_tests, 't_statistic', metrics)

# Table 4: Significance status (True = significant after correction)
significance_table = create_results_table(all_tests, 'rejected_holm', metrics)

print("ORIGINAL P-VALUES")
print("="*50)
print(p_values_table.round(4))

print("\n\nHOLM-BONFERRONI CORRECTED P-VALUES")
print("="*50)
print(p_corrected_table.round(4))

print("\n\nT-STATISTICS")
print("="*50)
print(t_stats_table.round(3))

print("\n\nSIGNIFICANCE STATUS (after Holm-Bonferroni correction)")
print("="*50)
print("True = Significant difference from paper results")
print(significance_table)

# Create a combined summary table showing key information
print("\n\nCOMBINED SUMMARY TABLE")
print("="*50)
combined_summary = pd.DataFrame(index=p_values_table.index)

for metric in metrics:
    # Format: "p_orig → p_corr (sig_status)"
    combined_summary[f'{metric}_p_original'] = p_values_table[metric].round(4)
    combined_summary[f'{metric}_p_corrected'] = p_corrected_table[metric].round(4)
    combined_summary[f'{metric}_significant'] = significance_table[metric]
    
    # Create a readable summary column
    combined_summary[f'{metric}_summary'] = combined_summary.apply(
        lambda row: f"{row[f'{metric}_p_original']:.3f} → {row[f'{metric}_p_corrected']:.3f} {'*' if row[f'{metric}_significant'] else ''}", 
        axis=1
    )

# Show just the summary columns for readability
summary_columns = [f'{metric}_summary' for metric in metrics]
print(combined_summary[summary_columns])

# Create a table showing differences from paper (Our - Paper)
print("\n\nDIFFERENCES FROM PAPER RESULTS (Our - Paper)")
print("="*50)
differences_table = pd.DataFrame(index=paper_df.index)

for metric in metrics:
    # Calculate differences (convert means back to same scale as paper)
    our_values = means.loc[paper_df.index, metric] * 100  # Convert to percentage
    paper_values = paper_df[metric]
    differences_table[metric] = our_values - paper_values

print(differences_table.round(2))

# Mark significant differences with asterisks
print("\n\nDIFFERENCES WITH SIGNIFICANCE MARKERS")
print("="*50)
print("* = Significant difference after Holm-Bonferroni correction")

differences_with_sig = differences_table.copy()
for metric in metrics:
    differences_with_sig[metric] = differences_with_sig[metric].round(2).astype(str)
    
    # Add asterisks for significant differences
    sig_mask = significance_table[metric]
    differences_with_sig.loc[sig_mask, metric] = differences_with_sig.loc[sig_mask, metric] + '*'

print(differences_with_sig)

# Save all tables
p_values_table.to_csv('p_values_original.csv')
p_corrected_table.to_csv('p_values_holm_corrected.csv')
t_stats_table.to_csv('t_statistics.csv')
significance_table.to_csv('significance_status.csv')
differences_with_sig.to_csv('differences_from_paper.csv')

print(f"\n\nAll tables saved as CSV files:")
print("- p_values_original.csv")
print("- p_values_holm_corrected.csv") 
print("- t_statistics.csv")
print("- significance_status.csv")
print("- differences_from_paper.csv")

ORIGINAL P-VALUES
==================================================
                      Accuracy     IoU      AP
10 2  False original    0.8894  0.0038  0.0010
   5  False original    0.3944  0.1221  0.2873
   15 False original    0.0002  0.7711  0.0047
20 2  False original    0.0757  0.5423  0.9718
   5  False original    0.0036  0.0036  0.0029
   15 False original    0.0014  0.0087  0.0031
50 2  False original    0.0318  0.0177  0.1019
   5  False original    0.2378  0.3596  0.2846
   15 False original    0.0000  0.0001  0.0006


HOLM-BONFERRONI CORRECTED P-VALUES
==================================================
                      Accuracy     IoU      AP
10 2  False original    1.0000  0.0677  0.0236
   5  False original    1.0000  1.0000  1.0000
   15 False original    0.0057  1.0000  0.0750
20 2  False original    0.9079  1.0000  1.0000
   5  False original    0.0677  0.0677  0.0601
   15 False original    0.0297  0.1300  0.0612
50 2  False original    0.4138  0.2477  1.0000
   5  False original    1.0000  1.0000  1.0000
   15 False original    0.0003  0.0020  0.0153


T-STATISTICS
==================================================
                      Accuracy     IoU     AP
10 2  False original     0.146   5.101  6.831
   5  False original    -0.931  -1.859 -1.191
   15 False original     9.427  -0.307 -4.846
20 2  False original    -2.235  -0.653 -0.037
   5  False original    -5.168  -5.158 -5.435
   15 False original    -6.431  -4.179 -5.353
50 2  False original    -2.951  -3.478 -2.000
   5  False original    -1.340  -1.008 -1.198
   15 False original   -17.197 -11.847 -7.574


SIGNIFICANCE STATUS (after Holm-Bonferroni correction)
==================================================
True = Significant difference from paper results
                      Accuracy    IoU     AP
10 2  False original     False  False   True
   5  False original     False  False  False
   15 False original      True  False  False
20 2  False original     False  False  False
   5  False original     False  False  False
   15 False original      True  False  False
50 2  False original     False  False  False
   5  False original     False  False  False
   15 False original      True   True   True


COMBINED SUMMARY TABLE
==================================================
                     Accuracy_summary      IoU_summary       AP_summary
10 2  False original   0.889 → 1.000    0.004 → 0.068   0.001 → 0.024 *
   5  False original   0.394 → 1.000    0.122 → 1.000    0.287 → 1.000
   15 False original  0.000 → 0.006 *   0.771 → 1.000    0.005 → 0.075
20 2  False original   0.076 → 0.908    0.542 → 1.000    0.972 → 1.000
   5  False original   0.004 → 0.068    0.004 → 0.068    0.003 → 0.060
   15 False original  0.001 → 0.030 *   0.009 → 0.130    0.003 → 0.061
50 2  False original   0.032 → 0.414    0.018 → 0.248    0.102 → 1.000
   5  False original   0.238 → 1.000    0.360 → 1.000    0.285 → 1.000
   15 False original  0.000 → 0.000 *  0.000 → 0.002 *  0.001 → 0.015 *


DIFFERENCES FROM PAPER RESULTS (Our - Paper)
==================================================
                                                                           Accuracy  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                              92.44
           5            False           original                              93.98
           15           False           original                              95.10
20         2            False           original                              92.21
           5            False           original                              94.29
           15           False           original                              95.22
50         2            False           original                              89.44
           5            False           original                              92.15
           15           False           original                              95.17

                                                                             IoU  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           20.94
           5            False           original                           38.14
           15           False           original                           54.66
20         2            False           original                           18.98
           5            False           original                           41.98
           15           False           original                           55.35
50         2            False           original                           16.73
           5            False           original                           35.22
           15           False           original                           54.63

                                                                              AP
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           19.79
           5            False           original                           31.46
           15           False           original                           39.81
20         2            False           original                           18.46
           5            False           original                           33.62
           15           False           original                           41.10
50         2            False           original                           17.89
           5            False           original                           28.87
           15           False           original                           41.80


DIFFERENCES WITH SIGNIFICANCE MARKERS
==================================================
* = Significant difference after Holm-Bonferroni correction
                                                                          Accuracy  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                             92.44
           5            False           original                             93.98
           15           False           original                             95.1*
20         2            False           original                             92.21
           5            False           original                             94.29
           15           False           original                            95.22*
50         2            False           original                             89.44
           5            False           original                             92.15
           15           False           original                            95.17*

                                                                              IoU  \
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                            20.94
           5            False           original                            38.14
           15           False           original                            54.66
20         2            False           original                            18.98
           5            False           original                            41.98
           15           False           original                            55.35
50         2            False           original                            16.73
           5            False           original                            35.22
           15           False           original                           54.63*

                                                                               AP
window_len train_config multiple_digits depth_channel_representation_mode
10         2            False           original                           19.79*
           5            False           original                            31.46
           15           False           original                            39.81
20         2            False           original                            18.46
           5            False           original                            33.62
           15           False           original                             41.1
50         2            False           original                            17.89
           5            False           original                            28.87
           15           False           original                            41.8*


All tables saved as CSV files:
- p_values_original.csv
- p_values_holm_corrected.csv
- t_statistics.csv
- significance_status.csv
- differences_from_paper.csv